// What a fired goal is allowed to *do*. The verbs mirror the browser engine's
// performAction() so a goal reads the same in either runtime; the difference is
// that these run with no tab open, so anything requiring a DOM (toast, open a
// URL) becomes an activity-log entry plus an optional webhook push.
//
//   notify <text>            push to the notify webhook + activity log
//   alert <text>             same, flagged as an alert
//   remember key = value     write to durable memory
//   scan watchlist           refresh every watched symbol, emit a signal table
//   research <topic>         run deep research, emit the cited brief
//   digest                   one-line summary of open goals and recent activity
//   log <text>               activity-log only, no outbound push

import { getState, rememberFact } from './store.js';
import { snapshot } from '../market/yahoo.js';
import { deepResearch } from './research.js';
import { sendNotification } from '../lib/notify.js';
import { localSignal } from '../lib/indicators.js';
import { log } from '../lib/log.js';

export function parseAction(text) {
  const a = String(text || '').trim();
  if (!a) return { kind: 'invalid', error: 'empty action' };

  let m;
  if ((m = a.match(/^(?:notify|toast)\s+(.+)$/i))) return { kind: 'notify', text: m[1] };
  if ((m = a.match(/^alert\s+(.+)$/i))) return { kind: 'alert', text: m[1] };
  if ((m = a.match(/^remember\s+(.+?)\s*=\s*(.+)$/i))) {
    return { kind: 'remember', key: m[1].trim(), value: m[2].trim() };
  }
  if (/^scan\s+watchlist$/i.test(a)) return { kind: 'scan' };
  if ((m = a.match(/^research\s+(.+)$/i))) return { kind: 'research', topic: m[1].trim() };
  if (/^digest$/i.test(a)) return { kind: 'digest' };
  if ((m = a.match(/^log\s+(.+)$/i))) return { kind: 'log', text: m[1] };

  return { kind: 'invalid', error: `unrecognised action: ${a}` };
}

/**
 * Expand $SYM references in notification text to the last known price, so
 * `alert NVDA crossed 140 (now $NVDA)` reads usefully in Slack.
 */
export async function expandSymbols(text) {
  const refs = [...String(text).matchAll(/\$([A-Z][A-Z0-9.\-]{0,9})/g)].map((m) => m[1]);
  if (!refs.length) return text;
  let out = text;
  for (const sym of [...new Set(refs)]) {
    try {
      const snap = await snapshot(sym);
      const price = snap.indicators?.last ?? snap.quote?.regularMarketPrice;
      if (price != null) out = out.replaceAll(`$${sym}`, `${sym} $${Number(price).toFixed(2)}`);
    } catch {
      /* leave the token as written */
    }
  }
  return out;
}

async function runScan() {
  const state = getState();
  const symbols = state.watchlist.map((w) => (typeof w === 'string' ? w : w.sym)).filter(Boolean);
  if (!symbols.length) {
    return { ok: false, summary: 'watchlist is empty', detail: null };
  }

  const rows = [];
  for (const sym of symbols) {
    try {
      const snap = await snapshot(sym);
      const ind = snap.indicators;
      const sig = ind ? localSignal(ind) : null;
      rows.push({
        symbol: sym,
        price: ind?.last ?? snap.quote?.regularMarketPrice ?? null,
        signal: sig?.label ?? '--',
        conviction: sig?.conv ?? '--',
        rsi: ind?.rsi ?? null,
        chgPct: ind?.chgPct ?? null,
      });
    } catch (err) {
      rows.push({ symbol: sym, error: err?.message || String(err) });
    }
  }

  const table = [
    '| Symbol | Price | Signal | RSI | 1D chg |',
    '|---|---|---|---|---|',
    ...rows.map((r) =>
      r.error
        ? `| ${r.symbol} | — | ERROR | — | — |`
        : `| ${r.symbol} | ${r.price != null ? `$${r.price.toFixed(2)}` : 'N/A'} | ${r.signal} ${r.conviction} | ${
            r.rsi != null ? r.rsi.toFixed(0) : '--'
          } | ${r.chgPct != null ? `${r.chgPct.toFixed(2)}%` : '--'} |`,
    ),
  ].join('\n');

  const markdown = `## Market Scan — ${new Date().toISOString()}\n${table}\n\n_Generated by the server autonomy loop. Not financial advice._`;
  const movers = rows.filter((r) => r.signal === 'BUY' || r.signal === 'SELL');
  const summary = `scanned ${rows.length} symbol(s)${
    movers.length ? `; ${movers.map((m) => `${m.symbol}=${m.signal}`).join(', ')}` : '; no signal changes'
  }`;

  return { ok: true, summary, detail: { markdown, rows } };
}

async function runDigest() {
  const state = getState();
  const armed = state.goals.filter((g) => g.enabled).length;
  const recent = state.activity.slice(-5).reverse();
  const lines = recent.map((a) => `- ${new Date(a.t).toISOString()} ${a.goal || a.kind}: ${a.summary}`);
  const markdown = [
    `## Agent digest — ${new Date().toISOString()}`,
    `Goals armed: ${armed}/${state.goals.length} · watchlist: ${state.watchlist.length} · memory: ${state.memory.length}`,
    '',
    lines.length ? lines.join('\n') : '_No activity recorded yet._',
  ].join('\n');
  return { ok: true, summary: `digest: ${armed} goal(s) armed, ${recent.length} recent event(s)`, detail: { markdown } };
}

/**
 * Execute a parsed action.
 *
 * @returns {Promise<{ok:boolean, summary:string, detail:object|null}>}
 */
export async function executeAction(action, ctx = {}) {
  switch (action.kind) {
    case 'notify':
    case 'alert': {
      const prefix = action.kind === 'alert' ? 'ALERT: ' : '';
      const text = prefix + (await expandSymbols(action.text));
      const delivery = await sendNotification(text);
      return {
        ok: true,
        // Report what was actually sent, not what was configured — with voice
        // on, those differ, and the activity log should match the phone.
        summary: delivery.message || text,
        detail: {
          delivered: delivery.delivered,
          reason: delivery.reason || null,
          voiced: delivery.voiced || null,
          written: delivery.message === text ? null : text,
        },
      };
    }

    case 'remember': {
      const fact = rememberFact(action.key, action.value);
      return { ok: true, summary: `remembered ${fact.k}`, detail: { fact } };
    }

    case 'log':
      return { ok: true, summary: action.text, detail: null };

    case 'scan':
      return runScan();

    case 'digest':
      return runDigest();

    case 'research': {
      const res = await deepResearch(action.topic, []);
      const summary = `research "${action.topic}": ${res.cited.length} source(s)`;
      if (ctx.notifyResearch !== false && res.cited.length) {
        await sendNotification(`${summary}\n${res.markdown.slice(0, 900)}`).catch(() => {});
      }
      return { ok: true, summary, detail: res };
    }

    default:
      log.warn(`refusing unknown action: ${action.error || action.kind}`);
      return { ok: false, summary: action.error || 'unknown action', detail: null };
  }
}
